export const TASK_SCHEDULE_SYNC_ERROR_PREFIX = 'plans.task_schedules.sync_errors.';

export const TASK_SCHEDULE_SYNC_ERROR_GENERIC = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}generic`;
export const TASK_SCHEDULE_SYNC_ERROR_MISSING_CROP_TEMPLATES = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_crop_templates`;
export const TASK_SCHEDULE_SYNC_ERROR_MISSING_CROP_BLUEPRINTS = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_crop_blueprints`;
export const TASK_SCHEDULE_SYNC_ERROR_MISSING_GENERAL_TEMPLATES = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_general_templates`;
export const TASK_SCHEDULE_SYNC_ERROR_MISSING_GENERAL_BLUEPRINTS = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_general_blueprints`;
export const TASK_SCHEDULE_SYNC_ERROR_MISSING_WEATHER = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_weather`;
export const TASK_SCHEDULE_SYNC_ERROR_EMPTY_GDD_PROGRESS = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}empty_gdd_progress`;
export const TASK_SCHEDULE_SYNC_ERROR_MISSING_GDD_TRIGGER = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_gdd_trigger`;
export const TASK_SCHEDULE_SYNC_ERROR_GDD_DATE_NOT_FOUND = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}gdd_date_not_found`;
export const TASK_SCHEDULE_SYNC_ERROR_MISSING_START_DATE = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_start_date`;
export const TASK_SCHEDULE_SYNC_ERROR_AGRR_UNAVAILABLE = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}agrr_unavailable`;

export const TASK_SCHEDULE_SYNC_CROP_WIZARD_LINK_KEY = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}crop_wizard_link`;
export const TASK_SCHEDULE_SYNC_MISSING_GDD_TRIGGER_WIZARD_LINK_KEY = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}missing_gdd_trigger_wizard_link`;
export const TASK_SCHEDULE_SYNC_GDD_DATE_NOT_FOUND_WIZARD_LINK_KEY = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}gdd_date_not_found_wizard_link`;
export const TASK_SCHEDULE_SYNC_PLAN_CONTEXT_LINK_KEY = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}plan_context_link`;
export const TASK_SCHEDULE_SYNC_CROP_STAGES_LINK_KEY = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}crop_stages_link`;
export const TASK_SCHEDULE_SYNC_GENERIC_PLAN_LINK_KEY = `${TASK_SCHEDULE_SYNC_ERROR_PREFIX}generic_plan_link`;
